#!/usr/bin/env python3
"""
TemplateComposer reference implementation in Python.

Algorithm validation for the C# version. Same string-based approach,
same merge rules, same output ordering.

Usage:
  python3 template_composer_reference.py BASE_FILE ROLE_FILE [--check]

If --check is provided, validates the output structure against the source files
(write_files count, runcmd count, etc.) using PyYAML as a sanity check.
"""
import re
import sys
from datetime import datetime, timezone
from dataclasses import dataclass, field
from typing import List, Dict, Optional


KEY_REGEX = re.compile(r'^([a-zA-Z_][a-zA-Z0-9_]*):(.*)$')
PLACEHOLDER_REGEX = re.compile(r'^(__[A-Z0-9_]+__)\s*$')

# Merge modes
SCALAR_ROLE_WINS = "scalar_role_wins"
LIST_CONCAT = "list_concat"           # base + role (base first)
LIST_UNION = "list_union"              # union with dedup, base order

MERGE_MODES = {
    'hostname':         SCALAR_ROLE_WINS,
    'manage_etc_hosts': SCALAR_ROLE_WINS,
    'package_update':   SCALAR_ROLE_WINS,
    'package_upgrade':  SCALAR_ROLE_WINS,
    'disable_root':     SCALAR_ROLE_WINS,
    'ssh_pwauth':       SCALAR_ROLE_WINS,
    'final_message':    SCALAR_ROLE_WINS,
    'packages':         LIST_UNION,
    'bootcmd':          LIST_CONCAT,
    'write_files':      LIST_CONCAT,
    'runcmd':           LIST_CONCAT,
}


@dataclass
class Section:
    """A logical chunk of the YAML, in source order."""
    kind: str  # "key" | "placeholder" | "header"
    key: Optional[str] = None         # for kind=key
    inline_value: Optional[str] = None  # for kind=key, if same-line value
    block_lines: List[str] = field(default_factory=list)  # for kind=key block content
    raw_text: Optional[str] = None     # for kind=placeholder, the verbatim line


def parse_sections(yaml_text: str) -> List[Section]:
    """Walk lines, identify column-0 keys and placeholders.
    
    Returns sections in source order. Comments and blank lines before the first
    section are dropped (they're file-level, regenerated by Compose).
    Comments within a section's block content are preserved.
    """
    sections: List[Section] = []
    current: Optional[Section] = None

    for raw_line in yaml_text.split('\n'):
        line = raw_line.rstrip('\r')

        # Before any section starts, skip leading comments / blank / shebang
        if current is None and (
            not line.strip()
            or line.startswith('#')
        ):
            continue

        # Detect column-0 lines that start a new section
        if line and line[0] not in (' ', '\t', '#'):
            m = KEY_REGEX.match(line)
            if m:
                # Top-level key
                current = Section(
                    kind='key',
                    key=m.group(1),
                    inline_value=m.group(2).strip() if m.group(2).strip() else None,
                    block_lines=[],
                )
                sections.append(current)
                continue

            pm = PLACEHOLDER_REGEX.match(line)
            if pm:
                # Placeholder marker — its own section, preserved verbatim
                current = None  # placeholders don't accumulate content
                sections.append(Section(
                    kind='placeholder',
                    raw_text=line,
                ))
                continue

            # Column-0 line that's neither key nor placeholder — error
            raise ValueError(
                f"Unrecognized column-0 line (not a key or placeholder): {line!r}"
            )

        # Continuation: belongs to the current section's block content
        if current is not None and current.kind == 'key':
            current.block_lines.append(line)

    return sections


def trim_trailing_blanks(lines: List[str]) -> List[str]:
    """Remove trailing blank lines but keep interior blanks."""
    end = len(lines)
    while end > 0 and not lines[end - 1].strip():
        end -= 1
    return lines[:end]


def extract_simple_list_items(block_lines: List[str]) -> List[str]:
    """Extract items from a YAML block list of simple scalars.
    
    For `packages:` style content. Items are lines starting with '  - '.
    Returns the item text (after the dash and space).
    """
    items = []
    for line in block_lines:
        stripped = line.lstrip()
        if stripped.startswith('- '):
            items.append(stripped[2:].strip())
    return items


def emit_scalar(out: List[str], section: Section) -> None:
    """Emit a scalar section. May be inline or block-form."""
    key = section.key
    if section.inline_value is not None:
        out.append(f"{key}: {section.inline_value}")
    elif section.block_lines:
        out.append(f"{key}:")
        for line in trim_trailing_blanks(section.block_lines):
            out.append(line)
    else:
        # Empty section — just emit the key
        out.append(f"{key}:")
    out.append("")


def emit_list_concat(out: List[str], base_section: Optional[Section],
                     role_section: Optional[Section], key: str) -> None:
    """Emit a list section as base+role concatenation."""
    if base_section is None and role_section is None:
        return
    out.append(f"{key}:")
    if base_section is not None:
        for line in trim_trailing_blanks(base_section.block_lines):
            out.append(line)
    if role_section is not None:
        for line in trim_trailing_blanks(role_section.block_lines):
            out.append(line)
    out.append("")


def emit_list_union(out: List[str], base_section: Optional[Section],
                    role_section: Optional[Section], key: str) -> None:
    """Emit a list section as base ∪ role with dedup, base order preserved."""
    if base_section is None and role_section is None:
        return
    seen = set()
    ordered: List[str] = []
    for sec in (base_section, role_section):
        if sec is None:
            continue
        for item in extract_simple_list_items(sec.block_lines):
            if item not in seen:
                seen.add(item)
                ordered.append(item)
    if not ordered:
        return
    out.append(f"{key}:")
    for item in ordered:
        out.append(f"  - {item}")
    out.append("")


def compose(base_yaml: str, role_yaml: str, base_name: str, role_name: str) -> str:
    """Compose base + role into a single cloud-init document."""
    base_sections = parse_sections(base_yaml)
    role_sections = parse_sections(role_yaml)
    
    # Index role sections by key for lookup
    role_by_key: Dict[str, Section] = {
        s.key: s for s in role_sections if s.kind == 'key'
    }
    consumed_role_keys = set()

    out: List[str] = []
    out.append("#cloud-config")
    out.append(f"# Composed by TemplateComposer from:")
    out.append(f"#   base: {base_name}")
    out.append(f"#   role: {role_name}")
    out.append(f"# Generated at: {datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}")
    out.append(f"# DO NOT EDIT — regenerate by running TemplateSeederService.")
    out.append("")

    # Walk base sections in source order. For each, emit the merged form.
    for bs in base_sections:
        if bs.kind == 'placeholder':
            out.append(bs.raw_text)
            out.append("")
            continue

        # bs is a key section
        key = bs.key
        rs = role_by_key.get(key)
        if rs is not None:
            consumed_role_keys.add(key)

        mode = MERGE_MODES.get(key, SCALAR_ROLE_WINS)
        if mode == SCALAR_ROLE_WINS:
            emit_scalar(out, rs if rs is not None else bs)
        elif mode == LIST_CONCAT:
            emit_list_concat(out, bs, rs, key)
        elif mode == LIST_UNION:
            emit_list_union(out, bs, rs, key)

    # Emit role-only keys (keys role has that base doesn't)
    for rs in role_sections:
        if rs.kind != 'key':
            continue
        if rs.key in consumed_role_keys:
            continue
        mode = MERGE_MODES.get(rs.key, SCALAR_ROLE_WINS)
        if mode == SCALAR_ROLE_WINS:
            emit_scalar(out, rs)
        elif mode == LIST_CONCAT:
            emit_list_concat(out, None, rs, rs.key)
        elif mode == LIST_UNION:
            emit_list_union(out, None, rs, rs.key)

    # Trim trailing blank lines, ensure single trailing newline
    while out and not out[-1]:
        out.pop()
    return '\n'.join(out) + '\n'


def main():
    if len(sys.argv) < 3:
        print("Usage: template_composer_reference.py BASE_FILE ROLE_FILE [--check]")
        sys.exit(2)
    base_path = sys.argv[1]
    role_path = sys.argv[2]
    check = '--check' in sys.argv

    with open(base_path) as f:
        base_yaml = f.read()
    with open(role_path) as f:
        role_yaml = f.read()

    composed = compose(
        base_yaml, role_yaml,
        base_name=base_path.split('/')[-1],
        role_name=role_path.split('/')[-1],
    )

    if check:
        # Substitute placeholders so PyYAML can parse, then check structure
        import yaml
        substituted = (composed
            .replace('__SSH_AUTHORIZED_KEYS_BLOCK__', '_test_ssh_keys: []')
            .replace('__PASSWORD_CONFIG_BLOCK__', '_test_password: {}'))
        try:
            doc = yaml.safe_load(substituted)
            print(f"=== composed validates as YAML ===")
            print(f"  top-level keys: {sorted(k for k in doc.keys() if not k.startswith('_test'))}")
            print(f"  packages: {len(doc.get('packages', []))}")
            print(f"  bootcmd: {len(doc.get('bootcmd', []))}")
            print(f"  write_files: {len(doc.get('write_files', []))}")
            print(f"  runcmd: {len(doc.get('runcmd', []))}")
            print(f"  hostname: {doc.get('hostname', '<absent>')}")
            print(f"  final_message: {doc.get('final_message', '<absent>')[:60] if doc.get('final_message') else '<absent>'}")
        except yaml.YAMLError as e:
            print(f"FAIL: composed output is not valid YAML: {e}", file=sys.stderr)
            print(composed)
            sys.exit(1)
    else:
        print(composed)


if __name__ == '__main__':
    main()
