#cloud-config

# DeCloud Relay VM Bootstrap Configuration

package_update: true
package_upgrade: true

packages:
  - wireguard
  - wireguard-tools
  - nginx
  - iptables
  - curl
  - net-tools
  - fail2ban
  - ufw

write_files:
  # WireGuard configuration template
  - path: /etc/wireguard/wg0.conf
    permissions: '0600'
    content: |
      [Interface]
      PrivateKey = __WIREGUARD_PRIVATE_KEY__
      Address = 10.20.0.1/16
      ListenPort = 51820
      PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
      PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
      
      # CGNAT node peers will be added dynamically via API
  
  # Nginx reverse proxy configuration
  - path: /etc/nginx/sites-available/relay-proxy
    permissions: '0644'
    content: |
      # Relay proxy configuration
      upstream cgnat_nodes {
          least_conn;
          # CGNAT node backends will be added dynamically
      }
      
      server {
          listen 80 default_server;
          listen [::]:80 default_server;
          
          server_name _;
          
          # Health check endpoint
          location /health {
              access_log off;
              return 200 "OK\n";
              add_header Content-Type text/plain;
          }
          
          # Proxy to CGNAT nodes
          location / {
              proxy_pass http://cgnat_nodes;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
              
              # WebSocket support
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection "upgrade";
          }
      }
  
  # Relay management API
  - path: /opt/decloud-relay/relay-api.py
    permissions: '0755'
    content: |
      #!/usr/bin/env python3
      """
      DeCloud Relay Management API
      Provides endpoints for dynamic peer/backend management
      """
      from http.server import HTTPServer, BaseHTTPRequestHandler
      import json
      import subprocess
      
      class RelayAPI(BaseHTTPRequestHandler):
          def do_POST(self):
              if self.path == '/api/relay/add-peer':
                  self.add_wireguard_peer()
              elif self.path == '/api/relay/add-backend':
                  self.add_nginx_backend()
              else:
                  self.send_error(404)
          
          def add_wireguard_peer(self):
              content_length = int(self.headers['Content-Length'])
              post_data = self.rfile.read(content_length)
              peer = json.loads(post_data)
              
              # Add WireGuard peer
              cmd = [
                  'wg', 'set', 'wg0',
                  'peer', peer['public_key'],
                  'allowed-ips', peer['tunnel_ip'] + '/32'
              ]
              
              result = subprocess.run(cmd, capture_output=True)
              
              if result.returncode == 0:
                  self.send_response(200)
                  self.end_headers()
                  self.wfile.write(b'Peer added')
              else:
                  self.send_error(500, result.stderr.decode())
          
          def add_nginx_backend(self):
              content_length = int(self.headers['Content-Length'])
              post_data = self.rfile.read(content_length)
              backend = json.loads(post_data)
              
              # Add backend to nginx upstream (requires nginx reload)
              # This is simplified - production would use nginx API or config templating
              
              self.send_response(200)
              self.end_headers()
              self.wfile.write(b'Backend added')
      
      if __name__ == '__main__':
          server = HTTPServer(('0.0.0.0', 8080), RelayAPI)
          server.serve_forever()

runcmd:
  # Enable IP forwarding
  - echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
  - sysctl -p
  
  # Configure firewall
  - ufw default deny incoming
  - ufw default allow outgoing
  - ufw allow 22/tcp comment "SSH"
  - ufw allow 51820/udp comment "WireGuard"
  - ufw allow 80/tcp comment "HTTP Proxy"
  - ufw allow 8080/tcp comment "Relay API"
  - ufw --force enable
  
  # Start WireGuard
  - systemctl enable wg-quick@wg0
  - systemctl start wg-quick@wg0
  
  # Configure Nginx
  - ln -sf /etc/nginx/sites-available/relay-proxy /etc/nginx/sites-enabled/
  - rm -f /etc/nginx/sites-enabled/default
  - systemctl enable nginx
  - systemctl restart nginx
  
  # Start relay API
  - python3 /opt/decloud-relay/relay-api.py &
  
  # Log completion
  - echo "DeCloud relay VM bootstrap complete" > /var/log/relay-bootstrap.log

final_message: "DeCloud Relay VM is ready!"