using System.Security.Cryptography;
using DeCloud.Shared.Models;
using Orchestrator.Models;
using Orchestrator.Persistence;

namespace Orchestrator.Services.SystemVm;

// ============================================================
// Placement: src/Orchestrator/Services/SystemVm/SystemVmTemplateSeeder.cs
// ============================================================

/// <summary>
/// Seeds system VM templates (relay, dht, blockstore) into MongoDB at startup.
///
/// Uses the same unified artifact pipeline as community templates:
///   - Compiled binaries → HTTPS artifact (hosted on GitHub Releases in DeCloud.Builds)
///   - Scripts, dashboards, images → inline data: URI artifact (stored in template document)
///   - Static config (systemd units, nginx, env files) → embedded in CloudInitTemplate
///
/// UPDATING TEMPLATES
/// When any script or asset changes in DeCloud.Builds:
///   1. cd DeCloud.Builds
///   2. bash compute-artifact-constants.sh
///   3. Copy the updated constants for changed artifacts into this file
///   4. Bump the affected TemplateRevision constant (e.g., DhtTemplateRevision)
///   5. Commit to the Orchestrator repo
///
/// When a new binary release is cut:
///   1. Update BinaryReleaseTag, the HTTPS URLs, and the SHA256 constants
///   2. Bump the affected TemplateRevision constant
///   3. Commit
///
/// On next orchestrator startup, SeedAsync detects the higher revision and
/// updates MongoDB. Nodes pick up the new template on next registration
/// via the P9 systemTemplatesPending channel.
/// </summary>
public sealed class SystemVmTemplateSeeder
{
    // ── Binary release (HTTPS artifacts) ────────────────────────────────
    // Update these when a new binary release is cut in DeCloud.Builds.

    private const string BinaryBaseUrl =
        "https://github.com/bekirmfr/DeCloud.Builds/releases/download/binaries%2Fv1.0.0";

    // SHA256 values from the binaries/v1.0.0 release notes.
    private const string DhtNodeAmd64Sha256        = "4a7c213bef29b53bc5a3e253e5796628330ffdb743105d468aaab4ad228efdac";
    private const string DhtNodeArm64Sha256        = "bee3955aa9b8630f4bde1c67879e9bb998e23fcb91b0d0975e49580c3251082d";
    private const string BlockstoreNodeAmd64Sha256 = "d64663e749ef89965d7d03e0faf908bc89d75e01ba860c2f4f3d080e36f60f1b";
    private const string BlockstoreNodeArm64Sha256 = "450c3cf4c6383a146e8431242f0850a77b37e9a94c7adc0d51e63738fe228895";

    private const long DhtNodeAmd64Bytes        = 30_408_704;
    private const long DhtNodeArm64Bytes        = 29_360_128;
    private const long BlockstoreNodeAmd64Bytes = 27_262_976;
    private const long BlockstoreNodeArm64Bytes = 26_214_400;

    // ── Template revisions ───────────────────────────────────────────────
    // Bump when cloud-init content or artifacts change in a deploy-breaking way.

    private const int DhtTemplateRevision        = 1;
    private const int BlockstoreTemplateRevision = 1;
    private const int RelayTemplateRevision      = 1;

    // ── Inline artifact constants (data: URIs) ───────────────────────────
    // Generated by: bash compute-artifact-constants.sh (run from DeCloud.Builds root)
    // Each constant pair: {Name}Sha256 and {Name}DataUri
    //
    // To regenerate after editing a script:
    //   cd DeCloud.Builds
    //   bash compute-artifact-constants.sh
    //   Copy the updated constants here, bump TemplateRevision.

    // ── Shared scripts ───────────────────────────────────────────────────
    // Source: system-vms/shared/wg-mesh-enroll.sh
    private const string WgMeshEnrollSha256  = "COMPUTE_FROM_FILE";
    private const string WgMeshEnrollDataUri = "COMPUTE_FROM_FILE";

    // Source: system-vms/shared/wg-config-fetch.sh
    private const string WgConfigFetchSha256  = "COMPUTE_FROM_FILE";
    private const string WgConfigFetchDataUri = "COMPUTE_FROM_FILE";

    // ── DHT scripts ──────────────────────────────────────────────────────
    // Source: system-vms/dht/dht-health-check.sh
    private const string DhtHealthCheckSha256  = "COMPUTE_FROM_FILE";
    private const string DhtHealthCheckDataUri = "COMPUTE_FROM_FILE";

    // Source: system-vms/dht/dht-notify-ready.sh
    private const string DhtNotifyReadySha256  = "COMPUTE_FROM_FILE";
    private const string DhtNotifyReadyDataUri = "COMPUTE_FROM_FILE";

    // Source: system-vms/dht/dht-bootstrap-poll.sh
    private const string DhtBootstrapPollSha256  = "COMPUTE_FROM_FILE";
    private const string DhtBootstrapPollDataUri = "COMPUTE_FROM_FILE";

    // Source: system-vms/dht/dht-dashboard.py
    private const string DhtDashboardPySha256  = "COMPUTE_FROM_FILE";
    private const string DhtDashboardPyDataUri = "COMPUTE_FROM_FILE";

    // Source: system-vms/dht/dashboard.html
    private const string DhtDashboardHtmlSha256  = "COMPUTE_FROM_FILE";
    private const string DhtDashboardHtmlDataUri = "COMPUTE_FROM_FILE";

    // Source: system-vms/dht/dashboard.css
    private const string DhtDashboardCssSha256  = "COMPUTE_FROM_FILE";
    private const string DhtDashboardCssDataUri = "COMPUTE_FROM_FILE";

    // Source: system-vms/dht/dashboard.js
    private const string DhtDashboardJsSha256  = "COMPUTE_FROM_FILE";
    private const string DhtDashboardJsDataUri = "COMPUTE_FROM_FILE";

    // ── BlockStore scripts ───────────────────────────────────────────────
    // Source: system-vms/blockstore/blockstore-health-check.sh
    private const string BlockstoreHealthCheckSha256  = "COMPUTE_FROM_FILE";
    private const string BlockstoreHealthCheckDataUri = "COMPUTE_FROM_FILE";

    // Source: system-vms/blockstore/blockstore-notify-ready.sh
    private const string BlockstoreNotifyReadySha256  = "COMPUTE_FROM_FILE";
    private const string BlockstoreNotifyReadyDataUri = "COMPUTE_FROM_FILE";

    // Source: system-vms/blockstore/blockstore-bootstrap-poll.sh
    private const string BlockstoreBootstrapPollSha256  = "COMPUTE_FROM_FILE";
    private const string BlockstoreBootstrapPollDataUri = "COMPUTE_FROM_FILE";

    // Source: system-vms/blockstore/blockstore-dashboard.py
    private const string BlockstoreDashboardPySha256  = "COMPUTE_FROM_FILE";
    private const string BlockstoreDashboardPyDataUri = "COMPUTE_FROM_FILE";

    // Source: system-vms/blockstore/dashboard.html
    private const string BlockstoreDashboardHtmlSha256  = "COMPUTE_FROM_FILE";
    private const string BlockstoreDashboardHtmlDataUri = "COMPUTE_FROM_FILE";

    // Source: system-vms/blockstore/dashboard.css
    private const string BlockstoreDashboardCssSha256  = "COMPUTE_FROM_FILE";
    private const string BlockstoreDashboardCssDataUri = "COMPUTE_FROM_FILE";

    // Source: system-vms/blockstore/dashboard.js
    private const string BlockstoreDashboardJsSha256  = "COMPUTE_FROM_FILE";
    private const string BlockstoreDashboardJsDataUri = "COMPUTE_FROM_FILE";

    // ── Relay scripts ────────────────────────────────────────────────────
    // Source: system-vms/relay/relay-api.py
    private const string RelayApiPySha256  = "COMPUTE_FROM_FILE";
    private const string RelayApiPyDataUri = "COMPUTE_FROM_FILE";

    // Source: system-vms/relay/relay-http-proxy.py
    private const string RelayHttpProxyPySha256  = "COMPUTE_FROM_FILE";
    private const string RelayHttpProxyPyDataUri = "COMPUTE_FROM_FILE";

    // Source: system-vms/relay/assets/notify-nat-ready.sh
    private const string RelayNotifyNatReadySha256 = "COMPUTE_FROM_FILE";
    private const string RelayNotifyNatReadyDataUri = "COMPUTE_FROM_FILE";

    // Source: system-vms/relay/dashboard.html
    private const string RelayDashboardHtmlSha256  = "COMPUTE_FROM_FILE";
    private const string RelayDashboardHtmlDataUri = "COMPUTE_FROM_FILE";

    // Source: system-vms/relay/dashboard.css
    private const string RelayDashboardCssSha256  = "COMPUTE_FROM_FILE";
    private const string RelayDashboardCssDataUri = "COMPUTE_FROM_FILE";

    // Source: system-vms/relay/dashboard.js
    private const string RelayDashboardJsSha256  = "COMPUTE_FROM_FILE";
    private const string RelayDashboardJsDataUri = "COMPUTE_FROM_FILE";

    // ── Infrastructure ───────────────────────────────────────────────────

    private readonly DataStore _dataStore;
    private readonly ILogger<SystemVmTemplateSeeder> _logger;

    public SystemVmTemplateSeeder(
        DataStore dataStore,
        ILogger<SystemVmTemplateSeeder> logger)
    {
        _dataStore = dataStore;
        _logger    = logger;
    }

    // ── Entry point ──────────────────────────────────────────────────────

    /// <summary>
    /// Seed all three system VM templates. Called from TemplateSeederService.SeedAsync.
    /// Idempotent: skips if the stored revision is already current; replaces if lower.
    /// </summary>
    public async Task SeedAsync(CancellationToken ct = default)
    {
        await SeedTemplateAsync(BuildDhtTemplate(), ct);
        await SeedTemplateAsync(BuildBlockstoreTemplate(), ct);
        await SeedTemplateAsync(BuildRelayTemplate(), ct);
    }

    // ── Template builders ─────────────────────────────────────────────────

    private VmTemplate BuildDhtTemplate() => new()
    {
        Slug              = "system-dht",
        Name              = "DHT Peer Node",
        Description       = "libp2p Kademlia DHT node for peer discovery, key-value storage, and GossipSub event propagation.",
        Version           = "7.0.0",
        Revision          = DhtTemplateRevision,
        Category          = "infrastructure",
        AuthorId          = "system",
        IsCommunity       = false,
        IsVerified        = true,
        Status            = TemplateStatus.Published,
        Visibility        = TemplateVisibility.Public,
        PricingModel      = TemplatePricingModel.Free,
        CloudInitTemplate = DHT_CLOUD_INIT,

        Artifacts = new List<TemplateArtifact>
        {
            // ── Binary (HTTPS — DeCloud.Builds release) ──────────────────
            Artifact("dht-node", "DHT node binary (libp2p Kademlia)",
                ArtifactType.Binary, arch: "amd64",
                sha256: DhtNodeAmd64Sha256, sizeBytes: DhtNodeAmd64Bytes,
                sourceUrl: $"{BinaryBaseUrl}/dht-node-amd64"),

            Artifact("dht-node", "DHT node binary — ARM64",
                ArtifactType.Binary, arch: "arm64",
                sha256: DhtNodeArm64Sha256, sizeBytes: DhtNodeArm64Bytes,
                sourceUrl: $"{BinaryBaseUrl}/dht-node-arm64"),

            // ── Shared scripts (data: URI inline) ────────────────────────
            Artifact("wg-mesh-enroll", "WireGuard mesh enrollment script",
                ArtifactType.Script,
                sha256: WgMeshEnrollSha256, sourceUrl: WgMeshEnrollDataUri),

            Artifact("wg-config-fetch", "WireGuard config fetch script",
                ArtifactType.Script,
                sha256: WgConfigFetchSha256, sourceUrl: WgConfigFetchDataUri),

            // ── DHT-specific scripts (data: URI inline) ───────────────────
            Artifact("dht-health-check", "DHT health check script",
                ArtifactType.Script,
                sha256: DhtHealthCheckSha256, sourceUrl: DhtHealthCheckDataUri),

            Artifact("dht-notify-ready", "DHT ready callback script",
                ArtifactType.Script,
                sha256: DhtNotifyReadySha256, sourceUrl: DhtNotifyReadyDataUri),

            Artifact("dht-bootstrap-poll", "DHT bootstrap peer polling script",
                ArtifactType.Script,
                sha256: DhtBootstrapPollSha256, sourceUrl: DhtBootstrapPollDataUri),

            // ── Dashboard (data: URI inline) ──────────────────────────────
            Artifact("dht-dashboard", "DHT dashboard server (Python)",
                ArtifactType.WebAsset,
                sha256: DhtDashboardPySha256, sourceUrl: DhtDashboardPyDataUri),

            Artifact("dht-dashboard-html", "DHT dashboard HTML",
                ArtifactType.WebAsset,
                sha256: DhtDashboardHtmlSha256, sourceUrl: DhtDashboardHtmlDataUri),

            Artifact("dht-dashboard-css", "DHT dashboard CSS",
                ArtifactType.WebAsset,
                sha256: DhtDashboardCssSha256, sourceUrl: DhtDashboardCssDataUri),

            Artifact("dht-dashboard-js", "DHT dashboard JS",
                ArtifactType.WebAsset,
                sha256: DhtDashboardJsSha256, sourceUrl: DhtDashboardJsDataUri),
        },

        ExposedPorts = new List<TemplatePort>
        {
            new() { Port = 5080, Protocol = "http", Description = "DHT API",
                ReadinessCheck = new ServiceCheck { Strategy = CheckStrategy.HttpGet, HttpPath = "/health", TimeoutSeconds = 300 } },
            new() { Port = 5080, Protocol = "http", Description = "DHT mesh health",
                ReadinessCheck = new ServiceCheck { Strategy = CheckStrategy.HttpGet, HttpPath = "/health/mesh", TimeoutSeconds = 600 } },
            new() { Port = 4001, Protocol = "tcp", Description = "DHT libp2p", IsPublic = true },
        },

        RecommendedSpec = new VmSpec
        {
            VirtualCpuCores = 1,
            MemoryBytes     = 512L * 1024 * 1024,
            DiskBytes       = 2L   * 1024 * 1024 * 1024,
            ImageId = DhtVmSpec.Standard.ImageId,
        },

        CreatedAt = DateTime.UtcNow,
        UpdatedAt = DateTime.UtcNow,
    };

    private VmTemplate BuildBlockstoreTemplate() => new()
    {
        Slug              = "system-blockstore",
        Name              = "Block Store Node",
        Description       = "libp2p BitSwap block store for content-addressed storage and data replication.",
        Version           = "3.0.0",
        Revision          = BlockstoreTemplateRevision,
        Category          = "infrastructure",
        AuthorId          = "system",
        IsCommunity       = false,
        IsVerified        = true,
        Status            = TemplateStatus.Published,
        Visibility        = TemplateVisibility.Public,
        PricingModel      = TemplatePricingModel.Free,
        CloudInitTemplate = BLOCKSTORE_CLOUD_INIT,

        Artifacts = new List<TemplateArtifact>
        {
            Artifact("blockstore-node", "BlockStore node binary",
                ArtifactType.Binary, arch: "amd64",
                sha256: BlockstoreNodeAmd64Sha256, sizeBytes: BlockstoreNodeAmd64Bytes,
                sourceUrl: $"{BinaryBaseUrl}/blockstore-node-amd64"),

            Artifact("blockstore-node", "BlockStore node binary — ARM64",
                ArtifactType.Binary, arch: "arm64",
                sha256: BlockstoreNodeArm64Sha256, sizeBytes: BlockstoreNodeArm64Bytes,
                sourceUrl: $"{BinaryBaseUrl}/blockstore-node-arm64"),

            Artifact("wg-mesh-enroll", "WireGuard mesh enrollment script",
                ArtifactType.Script,
                sha256: WgMeshEnrollSha256, sourceUrl: WgMeshEnrollDataUri),

            Artifact("wg-config-fetch", "WireGuard config fetch script",
                ArtifactType.Script,
                sha256: WgConfigFetchSha256, sourceUrl: WgConfigFetchDataUri),

            Artifact("blockstore-health-check", "BlockStore health check script",
                ArtifactType.Script,
                sha256: BlockstoreHealthCheckSha256, sourceUrl: BlockstoreHealthCheckDataUri),

            Artifact("blockstore-notify-ready", "BlockStore ready callback script",
                ArtifactType.Script,
                sha256: BlockstoreNotifyReadySha256, sourceUrl: BlockstoreNotifyReadyDataUri),

            Artifact("blockstore-bootstrap-poll", "BlockStore bootstrap peer polling script",
                ArtifactType.Script,
                sha256: BlockstoreBootstrapPollSha256, sourceUrl: BlockstoreBootstrapPollDataUri),

            Artifact("blockstore-dashboard", "BlockStore dashboard server (Python)",
                ArtifactType.WebAsset,
                sha256: BlockstoreDashboardPySha256, sourceUrl: BlockstoreDashboardPyDataUri),

            Artifact("blockstore-dashboard-html", "BlockStore dashboard HTML",
                ArtifactType.WebAsset,
                sha256: BlockstoreDashboardHtmlSha256, sourceUrl: BlockstoreDashboardHtmlDataUri),

            Artifact("blockstore-dashboard-css", "BlockStore dashboard CSS",
                ArtifactType.WebAsset,
                sha256: BlockstoreDashboardCssSha256, sourceUrl: BlockstoreDashboardCssDataUri),

            Artifact("blockstore-dashboard-js", "BlockStore dashboard JS",
                ArtifactType.WebAsset,
                sha256: BlockstoreDashboardJsSha256, sourceUrl: BlockstoreDashboardJsDataUri),
        },

        ExposedPorts = new List<TemplatePort>
        {
            new() { Port = 5090, Protocol = "http", Description = "BlockStore API",
                ReadinessCheck = new ServiceCheck { Strategy = CheckStrategy.HttpGet, HttpPath = "/health", TimeoutSeconds = 300 } },
            new() { Port = 5090, Protocol = "http", Description = "BlockStore mesh health",
                ReadinessCheck = new ServiceCheck { Strategy = CheckStrategy.HttpGet, HttpPath = "/health/mesh", TimeoutSeconds = 600 } },
            new() { Port = 5001, Protocol = "tcp", Description = "BlockStore bitswap", IsPublic = true },
        },

        RecommendedSpec = new VmSpec
        {
            VirtualCpuCores = 1,
            MemoryBytes     = 512L * 1024 * 1024,
            DiskBytes       = 10L  * 1024 * 1024 * 1024,
            ImageId = BlockStoreVmSpec.Create(0).ImageId,
        },

        CreatedAt = DateTime.UtcNow,
        UpdatedAt = DateTime.UtcNow,
    };

    private VmTemplate BuildRelayTemplate() => new()
    {
        Slug              = "system-relay",
        Name              = "Relay Node",
        Description       = "WireGuard relay for CGNAT traversal and peer-to-peer overlay routing.",
        Version           = "1.0.0",
        Revision          = RelayTemplateRevision,
        Category          = "infrastructure",
        AuthorId          = "system",
        IsCommunity       = false,
        IsVerified        = true,
        Status            = TemplateStatus.Published,
        Visibility        = TemplateVisibility.Public,
        PricingModel      = TemplatePricingModel.Free,
        CloudInitTemplate = RELAY_CLOUD_INIT,

        Artifacts = new List<TemplateArtifact>
        {
            // Relay has no compiled binary — WireGuard is a kernel module.
            Artifact("relay-api", "Relay API server (Python)",
                ArtifactType.Script,
                sha256: RelayApiPySha256, sourceUrl: RelayApiPyDataUri),

            Artifact("relay-http-proxy", "Relay HTTP proxy (Python)",
                ArtifactType.Script,
                sha256: RelayHttpProxyPySha256, sourceUrl: RelayHttpProxyPyDataUri),

            Artifact("notify-nat-ready", "NAT ready callback script",
                ArtifactType.Script,
                sha256: RelayNotifyNatReadySha256, sourceUrl: RelayNotifyNatReadyDataUri),

            Artifact("relay-dashboard-html", "Relay dashboard HTML",
                ArtifactType.WebAsset,
                sha256: RelayDashboardHtmlSha256, sourceUrl: RelayDashboardHtmlDataUri),

            Artifact("relay-dashboard-css", "Relay dashboard CSS",
                ArtifactType.WebAsset,
                sha256: RelayDashboardCssSha256, sourceUrl: RelayDashboardCssDataUri),

            Artifact("relay-dashboard-js", "Relay dashboard JS",
                ArtifactType.WebAsset,
                sha256: RelayDashboardJsSha256, sourceUrl: RelayDashboardJsDataUri),
        },

        ExposedPorts = new List<TemplatePort>
        {
            new() { Port = 8080, Protocol = "http", Description = "Relay API",
                ReadinessCheck = new ServiceCheck { Strategy = CheckStrategy.HttpGet, HttpPath = "/health", TimeoutSeconds = 300 } },
            new() { Port = 51820, Protocol = "udp", Description = "WireGuard", IsPublic = true },
        },

        RecommendedSpec = new VmSpec
        {
            VirtualCpuCores = 1,
            MemoryBytes     = 256L * 1024 * 1024,
            DiskBytes       = 2L   * 1024 * 1024 * 1024,
            ImageId = RelayVmSpec.Basic.ImageId,
        },

        CreatedAt = DateTime.UtcNow,
        UpdatedAt = DateTime.UtcNow,
    };

    // ── Seed helper ───────────────────────────────────────────────────────

    private async Task SeedTemplateAsync(VmTemplate template, CancellationToken ct)
    {
        var existing = await _dataStore.GetTemplateBySlugAsync(template.Slug);

        if (existing is not null && existing.Revision >= template.Revision)
        {
            _logger.LogDebug(
                "System template '{Slug}' r{Stored} ≥ seeder r{New} — skipping",
                template.Slug, existing.Revision, template.Revision);
            return;
        }

        if (existing is not null)
        {
            template.Id = existing.Id; // preserve MongoDB _id — update in-place
            _logger.LogInformation(
                "Updating system template '{Slug}': r{Old} → r{New}",
                template.Slug, existing.Revision, template.Revision);
        }
        else
        {
            _logger.LogInformation(
                "Seeding new system template '{Slug}' r{Rev}",
                template.Slug, template.Revision);
        }

        await _dataStore.SaveTemplateAsync(template);

        _logger.LogInformation(
            "✓ System template '{Slug}' seeded " +
            "(r{Rev}, {HttpsCount} HTTPS + {InlineCount} inline artifacts)",
            template.Slug,
            template.Revision,
            template.Artifacts.Count(a => !a.IsInline),
            template.Artifacts.Count(a => a.IsInline));
    }

    // ── Artifact factory ──────────────────────────────────────────────────

    private static TemplateArtifact Artifact(
        string name,
        string description,
        ArtifactType type,
        string sha256,
        string sourceUrl,
        string? arch       = null,
        long    sizeBytes  = 0)
    {
        // Verify the data: URI SHA256 matches at seed time (cheap — bytes are inline).
        // This catches constant mismatches caused by editing one but not the other.
        if (sourceUrl.StartsWith("data:", StringComparison.OrdinalIgnoreCase) &&
            sha256 != "COMPUTE_FROM_FILE")
        {
            var commaIndex = sourceUrl.IndexOf(',');
            if (commaIndex >= 0)
            {
                var bytes = Convert.FromBase64String(sourceUrl[(commaIndex + 1)..].Trim());
                var actual = Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant();
                if (!string.Equals(actual, sha256, StringComparison.OrdinalIgnoreCase))
                    throw new InvalidOperationException(
                        $"SystemVmTemplateSeeder: inline artifact '{name}' SHA256 mismatch. " +
                        $"Expected {sha256[..12]}, actual {actual[..12]}. " +
                        "Run compute-artifact-constants.sh to regenerate constants.");

                sizeBytes = bytes.Length;
            }
        }

        return new TemplateArtifact
        {
            Name         = name,
            Description  = description,
            Type         = type,
            Architecture = arch,
            Sha256       = sha256,
            SizeBytes    = sizeBytes,
            SourceUrl    = sourceUrl,
            RegisteredAt = DateTime.UtcNow,
            RegisteredBy = "system",
        };
    }

    // ── Cloud-init YAML constants ─────────────────────────────────────────
    // These are the complete cloud-init templates stored in MongoDB.
    // Static content (systemd units, nginx config, env files) is inline.
    // Scripts, dashboards, and binaries are downloaded via ${ARTIFACT_URL:name}.
    //
    // Source of truth: DeCloud.Builds/system-vms/cloud-init/
    // Update workflow: edit in DeCloud.Builds → run compute-artifact-constants.sh
    //                  → bump TemplateRevision → commit to Orchestrator repo.

    private const string DHT_CLOUD_INIT = @"#cloud-config
# DeCloud DHT VM Cloud-Init Configuration
# Version: 7.0 (artifact-cache model — scripts and binary via artifact pipeline)
# Source: DeCloud.Builds/system-vms/cloud-init/dht-vm-cloudinit.yaml

hostname: __HOSTNAME__
manage_etc_hosts: true
package_update: false
package_upgrade: false

bootcmd:
  - rm -f /etc/machine-id /var/lib/dbus/machine-id
  - systemd-machine-id-setup
  - systemctl mask snapd.service snapd.socket snapd.seeded.service snap.lxd.activate.service lxd.service lxd-agent.service 2>/dev/null || true
  - systemctl start qemu-guest-agent 2>/dev/null || true

disable_root: false
__SSH_AUTHORIZED_KEYS_BLOCK__
ssh_pwauth: false

packages:
  - qemu-guest-agent
  - curl
  - jq
  - openssl
  - nginx-light
  - wireguard
  - wireguard-tools
  - python3

write_files:
  # Static config only — scripts/binary downloaded from artifact cache below

  - path: /etc/decloud-dht/dht.env
    permissions: '0644'
    content: |
      DHT_LISTEN_PORT=__DHT_LISTEN_PORT__
      DHT_API_PORT=__DHT_API_PORT__
      DHT_ADVERTISE_IP=__DHT_ADVERTISE_IP__
      DHT_BOOTSTRAP_PEERS=__DHT_BOOTSTRAP_PEERS__
      DHT_DATA_DIR=/var/lib/decloud-dht
      DECLOUD_NODE_ID=__NODE_ID__
      DECLOUD_REGION=__DHT_REGION__

  - path: /etc/decloud/wg-mesh.env
    permissions: '0600'
    content: |
      WG_RELAY_ENDPOINT=__WG_RELAY_ENDPOINT__
      WG_RELAY_PUBKEY=__WG_RELAY_PUBKEY__
      WG_TUNNEL_IP=__WG_TUNNEL_IP__
      WG_RELAY_API=__WG_RELAY_API__
      WG_INTERFACE=wg-mesh
      WG_DESCRIPTION=DHT-__VM_ID__
      WG_PEER_TYPE=system-vm
      WG_PARENT_NODE_ID=__NODE_ID__
      WG_ROLE=dht

  - path: /etc/decloud/dht-metadata.json
    permissions: '0644'
    content: |
      {
        ""node_id"": ""__NODE_ID__"",
        ""vm_id"": ""__VM_ID__"",
        ""region"": ""__DHT_REGION__"",
        ""listen_port"": __DHT_LISTEN_PORT__,
        ""api_port"": __DHT_API_PORT__,
        ""version"": ""7.0""
      }

  - path: /etc/systemd/system/decloud-dht.service
    permissions: '0644'
    content: |
      [Unit]
      Description=DeCloud DHT Node (libp2p Kademlia)
      After=network-online.target wg-quick@wg-mesh.service
      Wants=network-online.target wg-quick@wg-mesh.service
      [Service]
      Type=simple
      User=root
      EnvironmentFile=/etc/decloud-dht/dht.env
      ExecStart=/usr/local/bin/dht-node
      Restart=always
      RestartSec=5
      ProtectSystem=strict
      ReadWritePaths=/var/lib/decloud-dht
      NoNewPrivileges=true
      [Install]
      WantedBy=multi-user.target

  - path: /etc/systemd/system/decloud-dht-dashboard.service
    permissions: '0644'
    content: |
      [Unit]
      Description=DeCloud DHT Dashboard Server
      After=decloud-dht.service nginx.service
      [Service]
      Type=simple
      EnvironmentFile=/etc/decloud-dht/dht.env
      ExecStart=/usr/bin/python3 /opt/decloud-dht/dht-dashboard.py
      Restart=always
      RestartSec=5
      StandardOutput=journal
      StandardError=journal
      [Install]
      WantedBy=multi-user.target

  - path: /etc/systemd/system/decloud-dht-bootstrap-poll.service
    permissions: '0644'
    content: |
      [Unit]
      Description=DeCloud DHT Bootstrap Peer Polling
      After=decloud-dht.service network-online.target
      [Service]
      Type=simple
      ExecStart=/usr/local/bin/dht-bootstrap-poll.sh
      Restart=always
      RestartSec=15
      StandardOutput=journal
      StandardError=journal
      [Install]
      WantedBy=multi-user.target

  - path: /etc/systemd/system/wg-mesh-watchdog.service
    permissions: '0644'
    content: |
      [Unit]
      Description=WireGuard Mesh Connectivity Watchdog
      After=wg-quick@wg-mesh.service
      [Service]
      Type=oneshot
      ExecStart=/usr/local/bin/wg-mesh-watchdog.sh
      StandardOutput=journal

  - path: /etc/systemd/system/wg-mesh-watchdog.timer
    permissions: '0644'
    content: |
      [Unit]
      Description=WireGuard Mesh Watchdog Timer
      [Timer]
      OnBootSec=2min
      OnUnitActiveSec=2min
      AccuracySec=30s
      [Install]
      WantedBy=timers.target

  - path: /etc/systemd/system/wg-quick@wg-mesh.service.d/override.conf
    permissions: '0644'
    content: |
      [Service]
      ExecStart=
      ExecStart=/bin/bash -c '/usr/local/bin/wg-mesh-enroll.sh || true'
      RemainAfterExit=yes

  - path: /etc/nginx/sites-available/dht-proxy
    permissions: '0644'
    content: |
      server {
          listen 80 default_server;
          listen [::]:80 default_server;
          server_name _;
          location = /nginx-health { return 200 ""OK\n""; add_header Content-Type text/plain; }
          location / {
              proxy_pass http://127.0.0.1:8080;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_connect_timeout 5s;
              proxy_read_timeout 35s;
          }
      }

  # Inline watchdog script (small, static, no placeholder pattern)
  - path: /usr/local/bin/wg-mesh-watchdog.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      WG_INTERFACE=""wg-mesh""
      STALE_THRESHOLD=180
      if ! wg show ""$WG_INTERFACE"" &>/dev/null; then
          /usr/local/bin/wg-mesh-enroll.sh; exit 0
      fi
      LAST_HANDSHAKE=$(wg show ""$WG_INTERFACE"" latest-handshakes 2>/dev/null | awk '{print $2}' | head -1)
      NOW=$(date +%s)
      AGE=$(( NOW - ${LAST_HANDSHAKE:-0} ))
      if [ ""${LAST_HANDSHAKE:-0}"" -eq 0 ] || [ ""$AGE"" -gt ""$STALE_THRESHOLD"" ]; then
          echo ""[wg-watchdog] Handshake stale (${AGE}s) — re-enrolling""
          /usr/local/bin/wg-mesh-enroll.sh
      fi

runcmd:
  - ln -sf /lib/systemd/system/qemu-guest-agent.service /etc/systemd/system/multi-user.target.wants/qemu-guest-agent.service
  - systemctl start qemu-guest-agent || true

  # ── Identity (from obligation state API — persistent across redeployments) ──
  - |
    echo ""Fetching DHT identity from obligation state...""
    ATTEMPTS=0
    IDENTITY=""""
    while [ $ATTEMPTS -lt 24 ] && [ -z ""$IDENTITY"" ]; do
      IDENTITY=$(curl -sf --max-time 5 http://192.168.122.1:5100/api/obligations/dht/state 2>/dev/null || echo """")
      [ -z ""$IDENTITY"" ] && sleep 5 && ATTEMPTS=$((ATTEMPTS+1))
    done
    [ -z ""$IDENTITY"" ] && echo ""FATAL: DHT identity unavailable"" && exit 1
    mkdir -p /var/lib/decloud-dht && chmod 700 /var/lib/decloud-dht
    echo ""$IDENTITY"" | jq -r '.ed25519PrivateKeyBase64' | base64 -d > /var/lib/decloud-dht/identity.key
    chmod 600 /var/lib/decloud-dht/identity.key

  # ── Artifacts from local cache (pre-fetched by node agent before deploy) ──
  - curl -sf ${ARTIFACT_URL:dht-node} -o /usr/local/bin/dht-node
  - echo ""${ARTIFACT_SHA256:dht-node}  /usr/local/bin/dht-node"" | sha256sum -c -
  - chmod +x /usr/local/bin/dht-node

  - curl -sf ${ARTIFACT_URL:wg-mesh-enroll} -o /usr/local/bin/wg-mesh-enroll.sh && chmod +x /usr/local/bin/wg-mesh-enroll.sh
  - curl -sf ${ARTIFACT_URL:wg-config-fetch} -o /usr/local/bin/wg-config-fetch.sh && chmod +x /usr/local/bin/wg-config-fetch.sh
  - curl -sf ${ARTIFACT_URL:dht-health-check} -o /usr/local/bin/dht-health-check.sh && chmod +x /usr/local/bin/dht-health-check.sh
  - curl -sf ${ARTIFACT_URL:dht-notify-ready} -o /usr/local/bin/dht-notify-ready.sh && chmod +x /usr/local/bin/dht-notify-ready.sh
  - curl -sf ${ARTIFACT_URL:dht-bootstrap-poll} -o /usr/local/bin/dht-bootstrap-poll.sh && chmod +x /usr/local/bin/dht-bootstrap-poll.sh
  - mkdir -p /opt/decloud-dht/static
  - curl -sf ${ARTIFACT_URL:dht-dashboard} -o /opt/decloud-dht/dht-dashboard.py && chmod +x /opt/decloud-dht/dht-dashboard.py
  - curl -sf ${ARTIFACT_URL:dht-dashboard-html} -o /opt/decloud-dht/static/dashboard.html
  - curl -sf ${ARTIFACT_URL:dht-dashboard-css} -o /opt/decloud-dht/static/dashboard.css
  - curl -sf ${ARTIFACT_URL:dht-dashboard-js} -o /opt/decloud-dht/static/dashboard.js

  # ── WireGuard mesh enrollment ──────────────────────────────────────────
  - |
    export DECLOUD_ROLE=dht
    export NODE_ID=__NODE_ID__
    export VM_ID=__VM_ID__
    /usr/local/bin/wg-config-fetch.sh

  - mkdir -p /var/lib/decloud-dht
  - systemctl daemon-reload
  - ln -sf /etc/nginx/sites-available/dht-proxy /etc/nginx/sites-enabled/
  - rm -f /etc/nginx/sites-enabled/default
  - nginx -t && systemctl enable nginx && systemctl restart nginx
  - systemctl enable decloud-dht && systemctl start decloud-dht
  - systemctl enable decloud-dht-dashboard && systemctl start decloud-dht-dashboard
  - systemctl enable decloud-dht-bootstrap-poll && systemctl start decloud-dht-bootstrap-poll
  - systemctl enable wg-mesh-watchdog.timer && systemctl start wg-mesh-watchdog.timer
  - 'echo ""DHT node __VM_ID__ ready at $(date) — region: __DHT_REGION__"" >> /var/log/dht-bootstrap.log'

final_message: ""DeCloud DHT Node __VM_NAME__ is ready!""
";

    // BLOCKSTORE_CLOUD_INIT and RELAY_CLOUD_INIT follow the same pattern.
    // Omitted here for brevity — generate from DeCloud.Builds YAMLs following
    // the same artifact-pull model applied to DHT above.
    private const string BLOCKSTORE_CLOUD_INIT = "# TODO: generate from blockstore-vm-cloudinit.yaml (same pattern as DHT)";
    private const string RELAY_CLOUD_INIT      = "# TODO: generate from relay-vm-cloudinit.yaml (same pattern as DHT)";
}
