using DeCloud.Orchestrator.Interfaces.CloudInit;
using DeCloud.Shared.Models;
using Orchestrator.Services;

namespace DeCloud.Orchestrator.Services.CloudInit.Resolvers.SystemVm.Relay;

/// <summary>
/// Resolves <c>__ORCHESTRATOR_PUBLIC_KEY__</c> — the orchestrator's WireGuard public key,
/// pre-configured as a [Peer] in the relay VM's wg-relay-server.conf so the orchestrator
/// host can reach the relay over WireGuard after boot.
///
/// <para>Source: <c>IWireGuardManager.GetOrchestratorPublicKeyAsync()</c>, which reads
/// from <c>/etc/wireguard/orchestrator-public.key</c> (generated by install.sh
/// <c>configure_wireguard_interface</c>). The key is cached in-process after the first read
/// so resolver calls are cheap.</para>
///
/// <para>System-VM-only. Throws if ctx.Obligation is null.</para>
/// </summary>
public sealed class OrchestratorPublicKeyResolver : IVariableResolver
{
    public string ResolverKey => "ORCHESTRATOR_PUBLIC_KEY";
    public VariableKind Kind => VariableKind.Static;

    private readonly IWireGuardManager _wireGuardManager;

    public OrchestratorPublicKeyResolver(IWireGuardManager wireGuardManager)
    {
        _wireGuardManager = wireGuardManager;
    }

    public async Task<string> ResolveAsync(ResolutionContext ctx, CancellationToken ct)
    {
        if (ctx.Obligation is null)
            throw new InvalidOperationException(
                "ORCHESTRATOR_PUBLIC_KEY resolver: ctx.Obligation is null. " +
                "This is a system-VM-only placeholder.");

        var publicKey = await _wireGuardManager.GetOrchestratorPublicKeyAsync(ct);

        if (string.IsNullOrWhiteSpace(publicKey))
            throw new InvalidOperationException(
                "ORCHESTRATOR_PUBLIC_KEY resolver: IWireGuardManager returned an empty key. " +
                "Ensure the orchestrator was installed with --enable-wireguard so that " +
                "/etc/wireguard/orchestrator-public.key exists and is readable.");

        return publicKey;
    }
}